import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { Header } from "@/components/ui/header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import SideBarcomp from "@/components/ui/SideBarcomp";
CreatedocumentProvider
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import SheetComp from "@/components/SheetComp";
import { CreatedocumentProvider } from "@/components/context/newdocumentprovider";
import UserAcc from "@/components/context/User";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <UserAcc />
          <Header />
          <CreatedocumentProvider>
            <SidebarProvider>
              <div className="flex flex-row">
                <SheetComp />
                <SidebarTrigger className="hidden md:inline" />

                <SideBarcomp />
                {children}
              </div>
            </SidebarProvider>
          </CreatedocumentProvider>
        </Provider>
      </body>
    </html>
  );
}
